variables:
  MAVEN_OPTS: "-Xms64m -Xmx256m -Djava.awt.headless=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true"


.template:
  stage: test
  image: maven:${TAG}
  script:
    - >-
      mvn -B -V
      deploy site site:stage
      -DaltDeploymentRepository=does_not_matter::file:///tmp/repo1

required:
  extends: .template
  parallel:
    matrix:
      - TAG: 3.8.5-eclipse-temurin-8
      - TAG: 3.8.5-eclipse-temurin-11

optional:
  extends: .template
  parallel:
    matrix:
      - TAG: 3.8.5-eclipse-temurin-17
  allow_failure: true
  
