language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
install: "mvn validate"
script: "mvn clean verify site"
branches:
    except:
        - gh-pages
notifications:
    email:
        - mfriedenhagen@gmail.com
