language: java
jdk:
  - oraclejdk7
install: "mvn --show-version --errors --batch-mode validate dependency:go-offline"
script: "mvn --show-version --errors --batch-mode -Dversions.skip=true clean verify site"
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - mfriedenhagen@gmail.com
