language: java
git:
  quiet: true
sudo: no
env:
  - MVN=3.5.4
  - MVN=3.6.0
jdk:
  - openjdk8
  - openjdk11
install:
  - mvn -B -N -q io.takari:maven:wrapper -Dmaven=3.5.4
script:
  - export MAVEN_OPTS="-Xms64m -Xmx256m -Djava.awt.headless=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true"
  - ./mvnw -B -Dversions.skip=true -DaltDeploymentRepository=does_not_matter::file:///tmp/repo1 clean verify site
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - mfriedenhagen@gmail.com
